//! Renders `SETTINGS.md`, at the repository root, from
//! `cfformat::options::reference()` and fails when the checked-in file
//! differs. Every example is the table's source formatted by `format_source`
//! with the shown value, so the reference cannot disagree with the formatter.
//! `UPDATE_REFERENCE=1` rewrites the file. The
//! `islands.*` examples format with `"oxc"`, in process, with
//! `islands.config` `"off"`.

use std::path::Path;

use cfformat::options::{reference, ExampleMode, Kind, OptionInfo, SEPARATOR_EXAMPLES};
use cfformat::{format_source, Options};
use cfparse::Mode;
use serde_json::{Map, Value};

fn kind_name(kind: Kind) -> String {
    match kind {
        Kind::Bool => "_boolean_".into(),
        Kind::Integer => "_integer_".into(),
        Kind::Enum(values) => {
            let values: Vec<String> = values
                .iter()
                .map(|v| format!("`{}`", serde_json::to_string(v).unwrap()))
                .collect();
            format!("_string_: {}", values.join(", "))
        }
        Kind::Separator => "_string_: `:` or `=` with at most one space on each side".into(),
    }
}

/// The values an example is shown with, as JSON literals.
fn shown_values(info: &OptionInfo) -> Vec<String> {
    let example = info.example.expect("an example");
    if !example.values.is_empty() {
        return example.values.iter().map(|v| v.to_string()).collect();
    }
    match info.kind {
        Kind::Bool => vec!["true".into(), "false".into()],
        Kind::Enum(values) => values
            .iter()
            .map(|v| serde_json::to_string(v).unwrap())
            .collect(),
        Kind::Separator => SEPARATOR_EXAMPLES.iter().map(|s| s.to_string()).collect(),
        Kind::Integer => panic!("`{}` must list its values", info.key),
    }
}

fn render() -> String {
    let mut out = String::from(
        "# Settings Reference\n\n\
         <!-- Generated by crates/cfformat/tests/reference.rs from \
         cfformat::options::reference(); run `UPDATE_REFERENCE=1 cargo test -p cfformat --test \
         reference` to update. -->\n\n\
         Every example below is the formatter's own output for that value, with the other \
         settings at their defaults unless noted.\n\n\
         The `*.multiline.element_count` and `*.multiline.min_item_length` pairs work \
         together: a list with at least `element_count` items whose items average more than \
         `min_item_length` columns on one line is always printed one item per line. \
         `element_count` is 0 by default, which turns this off, as Prettier has no such rule; \
         then, and for any list the pair does not force, the ordinary rules decide: the list \
         breaks when it does not fit within `max_columns` (counted from the column it starts \
         at) or holds something that cannot be printed on one line, such as a line comment or a \
         multiline string, and stays on one line otherwise. With `array.multiline.element_count` \
         set to 4, `x = ['january', 'february', 'march', 'april'];` breaks (its elements \
         average more than 8 columns) while `x = [1, 2, 3, 4, 5, 6];` stays on one line however many \
         elements it has. CommandBox cfformat's `*.multiline.min_length` measured the whole \
         list's width instead, so a long list of tiny items broke; a settings file that sets it \
         loads with a warning and the key is ignored.\n",
    );
    for info in reference() {
        out.push_str(&format!("\n## {}\n\n", info.key));
        out.push_str(&format!("Type: {}\n\n", kind_name(info.kind)));
        out.push_str(&format!("Default: **`{}`**\n\n", info.default));
        out.push_str(info.description);
        out.push('\n');
        let Some(example) = info.example else {
            continue;
        };
        let Value::Object(base) = serde_json::from_str::<Value>(example.settings).unwrap() else {
            panic!("`{}`: example settings are not an object", info.key);
        };
        if !base.is_empty() {
            let pairs: Vec<String> = base.iter().map(|(k, v)| format!("`{k}: {v}`")).collect();
            out.push_str(&format!("\nWith {}:\n", pairs.join(", ")));
        }
        for value in shown_values(info) {
            let mut settings: Map<String, Value> = Map::new();
            settings.insert("newline".into(), Value::from("\n"));
            // No `.prettierrc` above the checkout moves an island example.
            settings.insert("islands.config".into(), Value::from("off"));
            settings.extend(base.clone());
            settings.insert(info.key.into(), serde_json::from_str(&value).unwrap());
            let (opts, warnings) = Options::from_map(settings)
                .unwrap_or_else(|e| panic!("`{}` = {value}: {e}", info.key));
            assert!(warnings.is_empty(), "`{}`: {warnings:?}", info.key);
            let mode = match example.mode {
                ExampleMode::Script => Mode::Script,
                ExampleMode::Tags => Mode::Auto,
            };
            let formatted = format_source(example.source, mode, &opts);
            out.push_str(&format!(
                "\n```cfc\n// {}: {value}\n{formatted}```\n",
                info.key
            ));
        }
    }
    out
}

#[test]
fn reference_md_is_up_to_date() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../SETTINGS.md");
    let rendered = render();
    if std::env::var_os("UPDATE_REFERENCE").is_some() {
        std::fs::write(&path, &rendered).unwrap();
        return;
    }
    let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
    if on_disk != rendered {
        let diff = similar::TextDiff::from_lines(&on_disk, &rendered);
        panic!(
            "SETTINGS.md is out of date (UPDATE_REFERENCE=1 rewrites it):\n{}",
            diff.unified_diff()
                .context_radius(2)
                .header("SETTINGS.md", "rendered")
        );
    }
}
