use std::env;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();

    println!("cargo:rerun-if-changed=data");

    write_name_lists(Path::new(&manifest_dir), Path::new(&out_dir));
}

// ---------------------------------------------------------------------------
// Name lists for the hand-written script front end (`src/script/`)
// ---------------------------------------------------------------------------

/// `data/<file>.json` → `OUT_DIR/name_lists.rs` constant. Each file is one
/// JSON array of lowercase names, sorted: the built-in functions and tags
/// in script the script front end recognises by name, looked up by binary
/// search.
const NAME_LISTS: [(&str, &str); 2] = [
    ("support_functions", "SUPPORT_FUNCTIONS"),
    ("script_tags", "TAGS_IN_SCRIPT"),
];

fn write_name_lists(manifest: &Path, out_dir: &Path) {
    let mut rust = String::from("// Generated by build.rs from `data/*.json`.\n");
    for (file, konst) in NAME_LISTS {
        let path = manifest.join("data").join(format!("{file}.json"));
        let text =
            std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let names = json_strings(&text)
            .unwrap_or_else(|| panic!("{}: not a JSON array of names", path.display()));
        assert!(
            names.windows(2).all(|w| w[0] < w[1]),
            "{}: names must be sorted and unique",
            path.display()
        );
        assert!(
            names.iter().all(|n| !n.is_empty()
                && n.chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')),
            "{}: names must be lowercase identifiers",
            path.display()
        );
        assert!(
            names.len() > 100,
            "{}: only {} names",
            path.display(),
            names.len()
        );
        rust.push_str(&format!(
            "pub(crate) static {konst}: &[&str] = &[\n{}];\n",
            names
                .iter()
                .map(|n| format!("    {n:?},\n"))
                .collect::<String>()
        ));
    }
    std::fs::write(out_dir.join("name_lists.rs"), rust).expect("write name_lists.rs");
}

/// The strings of a flat JSON array of escape-free strings.
fn json_strings(text: &str) -> Option<Vec<String>> {
    let body = text.trim().strip_prefix('[')?.strip_suffix(']')?;
    let mut out = Vec::new();
    for part in body.split(',') {
        let part = part.trim();
        if part.is_empty() && out.is_empty() {
            continue;
        }
        let name = part.strip_prefix('"')?.strip_suffix('"')?;
        if name.contains(['"', '\\']) {
            return None;
        }
        out.push(name.to_string());
    }
    Some(out)
}
